import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {ActivityIndicator,AppState,BackHandler,Linking,Platform,SafeAreaView,ScrollView,Text,TextInput,TouchableOpacity,View,StyleSheet} from 'react-native';
import {CameraView,useCameraPermissions} from 'expo-camera';
import * as SecureStore from 'expo-secure-store';
import * as Crypto from 'expo-crypto';
import * as Location from 'expo-location';
import MapView,{Marker} from 'react-native-maps';
import {MobileClient,stationIdFromLink,validateCoreUrl,type Rental,type Station} from './client';
import {LocalNotificationAdapter,notificationFor} from './notifications';
import type {CustomerRentalSnapshot} from '../contracts/customer-api';
const notifier=Platform.OS!=='web'?new LocalNotificationAdapter():null;

type Mode='home'|'scan'|'station'|'return'|'receipt'|'history'|'support'|'settings'|'stations';
const configured=process.env.EXPO_PUBLIC_BATYEO_CORE_URL;
const demo=process.env.EXPO_PUBLIC_BATYEO_DEMO==='true';
const configError=(()=>{try{if(!configured)throw new Error('Configurez EXPO_PUBLIC_BATYEO_CORE_URL pour connecter l’application.');validateCoreUrl(configured);if(demo&&process.env.EXPO_PUBLIC_BATYEO_ENV==='production')throw new Error('Le mode démo est interdit en production.');return '';}catch(e){return e instanceof Error?e.message:'Configuration invalide.';}})();
const client=new MobileClient(configured??'',{get:()=>SecureStore.getItemAsync('batyeo.customer.session.v1'),set:value=>SecureStore.setItemAsync('batyeo.customer.session.v1',value)},()=>Crypto.randomUUID(),fetch,Platform.OS==='web');
const money=(n:number)=>`${(n/100).toFixed(2).replace('.',',')} €`;
const labels:Record<string,string>={ACTIVE:'En cours',OVERDUE:'À restituer',LOST:'Perte définitive',COMPLETED:'Terminée',EJECTION_FAILED:'Éjection échouée',PAYMENT_FAILED:'Paiement refusé',EJECTING:'Préparation',RETURNED:'Retour enregistré',ERROR:'Vérification nécessaire',PAYMENT_AUTH:'Paiement en cours',CREATED:'Créée',RETURN_PENDING:'Retour en cours',CANCELLED:'Annulée',EXPIRED:'Expirée'};
export default function App(){
 const [mode,setMode]=useState<Mode>('home'),[rental,setRental]=useState<Rental|null>(null),[detail,setDetail]=useState<Rental|null>(null),[history,setHistory]=useState<Rental[]>([]),[stations,setStations]=useState<Station[]>([]),[pricing,setPricing]=useState<CustomerRentalSnapshot['pricing']|null>(null),[selected,setSelected]=useState<Station|null>(null);
 const [loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(''),[online,setOnline]=useState(false),[serverDemo,setServerDemo]=useState(false),[accepted,setAccepted]=useState(false),[query,setQuery]=useState(''),[qr,setQr]=useState('');
 const [email,setEmail]=useState(''),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[ticket,setTicket]=useState(''),[supportRental,setSupportRental]=useState<Rental|null>(null),[nearby,setNearby]=useState<{latitude:number;longitude:number}|null>(null),[mapView,setMapView]=useState(false);
 const [permission,requestPermission]=useCameraPermissions();const locked=useRef(false),scanLock=useRef(false),alive=useRef(true);
 const reminder=useRef<{rentalId:string;notificationId:string|null}|null>(null);const [reminderOn,setReminderOn]=useState<boolean|null>(null);
 const active=!!rental&&['ACTIVE','OVERDUE','RETURN_PENDING'].includes(rental.state);
 const refresh=useCallback(async()=>{if(configError){setLoading(false);return;}try{const [session,pub]=await Promise.all([client.current(),client.stations()]);if(!alive.current)return;setRental(session.rental);setStations(pub.stations);setPricing(pub.pricing);setServerDemo(pub.demo);setOnline(true);}catch(e){if(alive.current){setOnline(false);setError(e instanceof Error?e.message:'Connexion indisponible.');}}finally{if(alive.current)setLoading(false);}},[]);
 async function run(action:()=>Promise<void>){if(locked.current)return;locked.current=true;setWorking(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Action impossible.');}finally{locked.current=false;setWorking(false);}}
 function navigate(next:Mode){setMode(next);setError('');setAccepted(false);scanLock.current=false;}
 async function resolveQr(value:string){if(scanLock.current)return;scanLock.current=true;await run(async()=>{const id=stationIdFromLink(value,configured??'');if(!id)throw new Error('QR BATYEO invalide. Utilisez un QR de station.');const pub=await client.stations();const found=pub.stations.find(s=>s.publicId===id);if(!found)throw new Error('Station inconnue.');setStations(pub.stations);setPricing(pub.pricing);setSelected(found);setAccepted(false);setMode(active?'return':'station');});scanLock.current=false;}
 async function openScan(){navigate('scan');if(Platform.OS!=='web'&&!permission?.granted)await requestPermission();}
 async function openHistory(){navigate('history');await run(async()=>setHistory((await client.history()).rentals));}
 function support(context:Rental|null){setSupportRental(context);setTicket('');navigate('support');}
 async function openLink(url:string){try{const parsed=new URL(url);const trusted=parsed.protocol==='batyeo:'||parsed.origin===new URL(configured??'').origin;if(!trusted)throw new Error('Lien BATYEO invalide.');const handoff=parsed.searchParams.get('handoff');if(handoff){await run(async()=>{const session=await client.claim(handoff);setRental(session.rental);navigate('home');});}else await resolveQr(url);}catch(e){setError(e instanceof Error?e.message:'Lien invalide.');}}
 useEffect(()=>{alive.current=true;void (async()=>{await refresh();const url=await Linking.getInitialURL();if(url&&alive.current)await openLink(url);})();const links=Linking.addEventListener('url',({url})=>{void openLink(url);});const app=AppState.addEventListener('change',state=>{if(state==='active')void refresh();});const timer=setInterval(()=>{if(AppState.currentState==='active'&&!locked.current)void refresh();},15000);return()=>{alive.current=false;links.remove();app.remove();clearInterval(timer);};},[refresh]);
 useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(mode==='home')return false;navigate('home');return true;});return()=>sub.remove();},[mode]);
 /** Local on-device reminder only, 6h before the return deadline. No push credentials involved. */
 useEffect(()=>{if(!notifier)return;const current=rental;const due=!!current&&['ACTIVE','OVERDUE'].includes(current.state)&&current.deadline!==null;const prev=reminder.current;if(due&&prev?.rentalId===current!.id)return;void(async()=>{if(prev?.notificationId)await notifier.cancel(prev.notificationId).catch(()=>{});if(due&&current){const granted=await notifier.requestPermission();const id=granted?await notifier.schedule(notificationFor('deadline_reminder',Date.now(),current.deadline)).catch(()=>null):null;reminder.current={rentalId:current.id,notificationId:id};setReminderOn(granted);}else{reminder.current=null;}})();},[rental?.id,rental?.state,rental?.deadline]);
 const button=(label:string,onPress:()=>void,disabled=false)=><TouchableOpacity accessibilityRole="button" accessibilityState={{disabled:disabled||working}} style={[styles.button,(disabled||working)&&{opacity:0.45}]} disabled={disabled||working} onPress={onPress}><Text style={styles.buttonText}>{label}</Text></TouchableOpacity>;
 const external=(path:string)=>void run(async()=>{await Linking.openURL(new URL(path,configured).href);});
 const receipt=(item:Rental)=><><Text style={styles.eyebrow}>{item.state==='COMPLETED'?'BATTERIE RENDUE':labels[item.state]??item.state}</Text><Text style={styles.title}>{item.station?.venue.name??'Location BATYEO'}</Text><Text style={styles.caption}>Référence {item.id}</Text><Text style={styles.caption}>{new Date(item.createdAt).toLocaleString('fr-FR')} · {Math.floor(item.elapsedMs/60000)} min</Text><Text style={styles.total}>{money(item.amountCents)}</Text>{item.payment?<Text style={styles.caption}>Caution libérée : {money(item.payment.releasedCents)}</Text>:<Text style={styles.caption}>Le détail de la caution n’est pas disponible dans cet historique.</Text>}{item.returnStationId&&<Text style={styles.caption}>Retour : {stations.find(s=>s.id===item.returnStationId)?.venue.name??item.returnStationId}</Text>}{button('Signaler un problème',()=>support(item))}</>;
 const matching=stations.filter(s=>`${s.venue.name} ${s.venue.city}`.toLocaleLowerCase('fr').includes(query.trim().toLocaleLowerCase('fr'))).filter(s=>!active||(s.online&&s.freeSlots>0));
 // Coordinates are optional. Unknown coordinates never become a fabricated map marker.
 const coordinate=(s:Station)=>Number.isFinite(s.venue.latitude)&&Number.isFinite(s.venue.longitude)?{latitude:s.venue.latitude!,longitude:s.venue.longitude!}:null;
 if(nearby)matching.sort((a,b)=>{const distance=(s:Station)=>{const p=coordinate(s);return p?Math.hypot(p.latitude-nearby.latitude,(p.longitude-nearby.longitude)*Math.cos(nearby.latitude*Math.PI/180)):Infinity;};return distance(a)-distance(b);});
 const located=matching.map(s=>({station:s,point:coordinate(s)})).filter((x):x is {station:Station;point:{latitude:number;longitude:number}}=>x.point!==null);
 const region=nearby?{...nearby,latitudeDelta:0.05,longitudeDelta:0.05}:located.length?{latitude:located.reduce((sum,x)=>sum+x.point.latitude,0)/located.length,longitude:located.reduce((sum,x)=>sum+x.point.longitude,0)/located.length,latitudeDelta:0.5,longitudeDelta:0.5}:{latitude:46.6,longitude:2.4,latitudeDelta:8,longitudeDelta:8};
 let content:ReactNode;
 if(configError)content=<><Text style={styles.title}>Connexion à préparer</Text><Text style={styles.error}>{configError}</Text></>;
 else if(loading)content=<ActivityIndicator accessibilityLabel="Chargement de BATYEO" color="#19382c" size="large"/>;
 else if(mode==='scan')content=<><Text style={styles.title}>Scanner une station</Text>{Platform.OS!=='web'&&permission?.granted?<CameraView style={{height:280,width:'100%'}} barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={({data})=>{void resolveQr(data);}}/>:<Text style={styles.caption}>La caméra nécessite une permission sur téléphone. Vous pouvez aussi saisir le lien QR.</Text>}{Platform.OS!=='web'&&!permission?.granted&&button('Autoriser la caméra',()=>{void requestPermission();})}<TextInput accessibilityLabel="Lien QR de la station" style={styles.input} value={qr} onChangeText={setQr} placeholder="Collez le lien QR BATYEO" autoCapitalize="none"/>{button('Ouvrir la station',()=>{void resolveQr(qr);},!qr)}{demo&&serverDemo&&stations[0]&&button('Scanner la station démo',()=>{void resolveQr(new URL(`/rent/${stations[0].publicId}`,configured).href);})}</>;
 else if(mode==='stations')content=<><Text style={styles.title}>{active?'Où rendre la batterie ?':'Trouver une station'}</Text><TextInput accessibilityLabel="Rechercher une station" style={styles.input} placeholder="Ville, établissement…" value={query} onChangeText={setQuery}/>{button('Stations proches',()=>void run(async()=>{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')throw new Error('Position non autorisée. La liste reste disponible.');const result=await Location.getLastKnownPositionAsync();if(!result)throw new Error('Position indisponible. Recherchez une ville dans la liste.');setNearby(result.coords);} ))}{Platform.OS!=='web'&&button(mapView?'Voir la liste':'Voir la carte',()=>setMapView(!mapView))}<Text style={styles.caption}>{nearby?'Stations triées lorsque leurs coordonnées sont connues.':'La liste fonctionne sans localisation.'}</Text>{!matching.length&&<Text style={styles.caption}>Aucune station ne correspond à votre recherche.</Text>}{mapView&&Platform.OS!=='web'?<>{!located.length&&<Text style={styles.caption}>Aucune station géolocalisée pour cette recherche.</Text>}<MapView accessibilityLabel="Carte des bornes" style={styles.map} region={region} showsUserLocation={!!nearby}>{located.map(({station:s,point})=><Marker key={s.id} coordinate={point} title={s.venue.name} description={`${s.online?'En ligne':'Hors ligne'} · ${s.available} batteries · ${s.freeSlots} retours libres`} pinColor={s.online&&(!active||s.freeSlots>0)?'#19382c':'#9d3f35'} onCalloutPress={()=>{setSelected(s);navigate(active?'return':'station');}}/>)}</MapView></>:matching.map(s=><TouchableOpacity accessibilityRole="button" key={s.id} style={styles.historyRow} onPress={()=>{setSelected(s);navigate(active?'return':'station');}}><Text style={styles.historyTitle}>{s.venue.name}</Text><Text style={styles.caption}>{s.venue.city} · {s.online?'En ligne':'Hors ligne'} · {s.available} batteries · {s.freeSlots} retours libres</Text></TouchableOpacity>)}</>;
 else if((mode==='station'||mode==='return')&&selected)content=<><Text style={styles.title}>{selected.venue.name}</Text><Text style={styles.caption}>{selected.venue.address} · {selected.venue.city}</Text><Text style={styles.caption}>{selected.venue.hours}</Text><Text style={styles.availability}>{selected.online?'En ligne':'Hors ligne'} · {selected.available} batteries · {selected.freeSlots} places libres</Text>{mode==='return'?<>{serverDemo?<Text style={styles.caption}>Retour simulé : aucun matériel n’est commandé.</Text>:<Text style={styles.caption}>Insérez la batterie dans un emplacement compatible. BATYEO confirmera le retour détecté par la station.</Text>}{serverDemo?button('Simuler le retour',()=>void run(async()=>{const data=await client.action('customer/return',selected.publicId);setRental(data.rental);setDetail(data.rental);setMode('receipt');await refresh();}),!online||!selected.online||selected.freeSlots<1):button('Vérifier le retour',()=>void refresh())}</>:pricing&&<><Text style={styles.caption}>{money(pricing.hourlyCents)} / heure commencée · plafond {money(pricing.capCents)}</Text><Text style={styles.caption}>Caution temporaire {money(pricing.depositCents)} · retour sous {pricing.deadlineHours} h</Text><TouchableOpacity accessibilityRole="checkbox" accessibilityState={{checked:accepted}} onPress={()=>setAccepted(!accepted)}><Text style={styles.link}>{accepted?'☑':'☐'} J’accepte les conditions de location</Text></TouchableOpacity>{button('Lire les conditions',()=>external('/terms'))}{button(working?'Autorisation et préparation…':'Prendre une batterie',()=>void run(async()=>{const data=await client.action('start',selected.publicId);setRental(data.rental);setMode('home');await refresh();}),!accepted||!online||!selected.online||selected.available<1||active)}</>}</>;
 else if(mode==='history')content=<><Text style={styles.title}>Vos locations</Text>{!history.length&&<Text style={styles.caption}>Votre historique est vide.</Text>}{history.map(item=><TouchableOpacity key={item.id} accessibilityRole="button" style={styles.historyRow} onPress={()=>{setDetail(item);navigate('receipt');}}><Text style={styles.historyTitle}>{item.station?.venue.name??'BATYEO'}</Text><Text style={styles.caption}>{labels[item.state]??item.state} · {new Date(item.createdAt).toLocaleDateString('fr-FR')} · {money(item.amountCents)}</Text></TouchableOpacity>)}{button('Actualiser l’historique',()=>void openHistory())}</>;
 else if(mode==='receipt'&&detail)content=receipt(detail);
 else if(mode==='support')content=ticket?<><Text style={styles.title}>Demande enregistrée</Text><Text style={styles.caption}>Référence : {ticket}</Text><Text style={styles.caption}>Retrouvez cette référence pour votre suivi. Aucun email automatique n’est promis.</Text>{button('Nouvelle demande',()=>{setTicket('');setMessage('');setSubject('');})}</>:<><Text style={styles.title}>Comment vous aider ?</Text>{supportRental&&<Text style={styles.caption}>Location : {supportRental.id}</Text>}<TextInput accessibilityLabel="Votre email" style={styles.input} value={email} onChangeText={setEmail} placeholder="Votre email" keyboardType="email-address" autoCapitalize="none"/><TextInput accessibilityLabel="Objet" style={styles.input} value={subject} onChangeText={setSubject} placeholder="Objet" maxLength={150}/><TextInput accessibilityLabel="Description du problème" style={[styles.input,styles.textarea]} value={message} onChangeText={setMessage} placeholder="Décrivez le problème" multiline maxLength={3000}/>{button('Envoyer la demande',()=>void run(async()=>{const result=await client.ticket(email.trim(),subject.trim(),message.trim(),supportRental?.id);setTicket(result.id);}),!/^\S+@\S+\.\S+$/.test(email)||subject.trim().length<3||message.trim().length<10)}</>;
 else if(mode==='settings')content=<><Text style={styles.title}>Votre espace BATYEO</Text><Text style={styles.caption}>Vos locations sont liées à votre session. Conservez cette application pour retrouver votre historique.</Text><Text style={styles.caption}>{Platform.OS==='web'?'Rappel de restitution : indisponible sur web.':reminderOn===null?'Rappel de restitution : activé automatiquement pendant une location.':reminderOn?'Rappel de restitution : activé.':'Rappel de restitution : autorisation refusée. Activez-la dans les réglages du téléphone.'}</Text>{button('Historique',()=>void openHistory())}{button('Confidentialité',()=>external('/privacy'))}{button('Conditions',()=>external('/terms'))}{button('Contacter le support',()=>support(rental))}</>;
 else if(rental)content=<><Text style={styles.eyebrow}>{labels[rental.state]??rental.state}</Text><Text style={styles.title}>{rental.station?.venue.name??'BATYEO'}</Text><Text style={styles.caption}>Durée : {Math.floor(rental.elapsedMs/60000)} min</Text><Text style={styles.total}>{money(rental.currentCents)} · max. {money(rental.pricing.capCents)}</Text>{rental.deadline&&<Text style={styles.caption}>À rendre avant le {new Date(rental.deadline).toLocaleString('fr-FR')}</Text>}{rental.error&&<Text style={styles.error}>{rental.error}</Text>}{active&&button('Trouver une station de retour',()=>navigate('stations'))}{rental.state==='COMPLETED'&&button('Voir le reçu',()=>{setDetail(rental);navigate('receipt');})}{['COMPLETED','CANCELLED','EXPIRED','PAYMENT_FAILED','EJECTION_FAILED','LOST'].includes(rental.state)&&button('Nouvelle location',()=>navigate('stations'))}{button('Actualiser la location',()=>void refresh())}{button('Signaler un problème',()=>support(rental))}</>;
 else content=<><Text style={styles.emptyTitle}>Votre prochaine recharge.</Text><Text style={styles.caption}>Trouvez une station ou scannez son QR pour commencer.</Text>{button('Scanner un QR code',()=>void openScan())}{button('Trouver une station',()=>navigate('stations'))}</>;
 return <SafeAreaView style={styles.screen}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.container}><TouchableOpacity accessibilityRole="button" accessibilityLabel="BATYEO accueil" onPress={()=>navigate('home')}><Text style={styles.brand}>batyeo<Text style={styles.dot}>.</Text></Text></TouchableOpacity><Text style={styles.headline}>Votre énergie,<Text style={styles.lime}> avec vous.</Text></Text>{serverDemo&&<Text style={{color:'#d8ed98'}}>DÉMONSTRATION · paiement et station simulés</Text>}{!online&&!loading&&!configError&&<Text style={{color:'#fff'}}>Connexion indisponible · données à actualiser</Text>}{error&&<View style={styles.card}><Text accessibilityRole="alert" style={styles.error}>{error}</Text>{button('Réessayer',()=>{setError('');void refresh();})}</View>}<View style={styles.card}>{working&&<ActivityIndicator accessibilityLabel="Opération en cours"/>}{content}</View><View style={styles.actions}>{(['home','stations','history','settings'] as const).map((next,i)=><TouchableOpacity accessibilityRole="button" key={next} onPress={()=>next==='history'?void openHistory():navigate(next)}><Text style={{color:'#d8ed98',paddingVertical:12}}>{['Accueil','Stations','Historique','Profil'][i]}</Text></TouchableOpacity>)}</View>{mode!=='home'&&button('Retour à l’accueil',()=>navigate('home'))}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#19382c'},container:{padding:28,gap:24,minHeight:'100%'},brand:{color:'#f4f6ee',fontSize:30,fontWeight:'800'},dot:{color:'#d8ed98'},headline:{color:'#f4f6ee',fontSize:38,lineHeight:43,fontWeight:'600'},lime:{color:'#d8ed98'},card:{backgroundColor:'#f7f8f2',borderRadius:18,padding:24,gap:16},scanner:{flex:1},scanOverlay:{flex:1,justifyContent:'flex-end',padding:28,gap:18},scanTitle:{color:'#fff',fontSize:24,fontWeight:'700'},scanError:{color:'#ffd7d0',fontSize:14},button:{backgroundColor:'#19382c',padding:16,borderRadius:10,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'700'},buttonLight:{backgroundColor:'#f7f8f2',padding:16,borderRadius:10,alignItems:'center'},buttonLightText:{color:'#19382c',fontWeight:'700'},error:{color:'#9d3f35',fontSize:15},emptyTitle:{color:'#19382c',fontSize:22,fontWeight:'600'},eyebrow:{color:'#6b8251',fontSize:11,fontWeight:'700',letterSpacing:1.5},title:{color:'#19382c',fontSize:27,fontWeight:'600'},caption:{color:'#71806f',fontSize:14,lineHeight:21},availability:{color:'#416647',fontSize:15,fontWeight:'600'},total:{color:'#19382c',fontSize:26,fontWeight:'700'},terms:{color:'#71806f',fontSize:12,lineHeight:18},historyRow:{borderBottomWidth:1,borderBottomColor:'#dbe3d8',paddingVertical:12,gap:4},map:{height:340,width:'100%',borderRadius:12},historyTitle:{color:'#19382c',fontSize:16,fontWeight:'600'},actions:{flexDirection:'row',flexWrap:'wrap',gap:18,paddingTop:4},link:{color:'#53704e',fontWeight:'600'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d5dfd3',borderRadius:10,padding:13,color:'#19382c',fontSize:15},textarea:{minHeight:100,textAlignVertical:'top'}});
