import test from 'node:test';
import assert from 'node:assert/strict';
import {seedData} from '../core/seed';
import {validateData} from '../core/invariants';
import type {Data} from '../core/types';
import type {Repository} from '../core/repository';
import type {ManufacturerDeviceSnapshot} from '../core/manufacturer';
import {ManufacturerError} from '../core/manufacturer';
import {ManufacturerSyncService,linkManufacturerStation,providerHealth} from '../core/manufacturer-sync';
import {dashboard} from '../core/queries';
import {createApi} from '../server/http';

class MemoryRepository implements Repository {constructor(public data:Data){}async read(){return structuredClone(this.data);}async transaction<T>(fn:(data:Data)=>T){const next=structuredClone(this.data),value=fn(next);validateData(next);this.data=next;return value;}}
const snapshot=(deviceId:string,online=true):ManufacturerDeviceSnapshot=>({deviceId,cabinetId:'cabinet',qrCode:'qr',online,totalSlots:4,emptySlots:1,busySlots:99,signal:'documented-value',type:'cabinet-type',ip:'10.0.0.1',shopId:'shop',shopName:'Demo',shopAddress:'Demo',latitude:null,longitude:null,batteries:[{id:'BAT-UNKNOWN',slot:1,voltage:4100}],slots:[{position:1,battery:{id:'BAT-UNKNOWN',slot:1,voltage:4100}},{position:2,battery:null},{position:3,battery:null},{position:4,battery:null}],availability:1,lastSeenAt:null});

test('manufacturer mapping prevents duplicate external IDs and supports provider registry',()=>{const data=seedData('x');const first=linkManufacturerStation(data,'station-paris','BAJIE','BJH02347',100);assert.equal(first.externalId,'BJH02347');assert.throws(()=>linkManufacturerStation(data,'station-lyon','BAJIE','BJH02347',101),/déjà associé/);validateData(data);});

test('read-only station sync persists normalized telemetry and reconciliation without overwriting BATYEO state',async()=>{const data=seedData('x');data.stations[0].online=false;linkManufacturerStation(data,'station-paris','BAJIE','BJH02347',100);const repo=new MemoryRepository(data),service=new ManufacturerSyncService(repo,{getDeviceInfo:async id=>snapshot(id,true)},{now:()=>200});const run=await service.run({trigger:'MANUAL'});assert.equal(run.status,'COMPLETED');assert.equal(repo.data.stations[0].online,false);assert.equal(repo.data.stations[0].providerStatus,'ONLINE');assert.equal(repo.data.stationProviderSnapshots[0].busySlots,99);assert.ok(repo.data.reconciliationRecords.some(row=>row.kind==='STATION_STATUS'&&row.status==='OPEN'));assert.ok(repo.data.reconciliationRecords.some(row=>row.kind==='UNKNOWN_BATTERY'));});

test('sync retries safe reads and continues when another station fails',async()=>{const data=seedData('x');linkManufacturerStation(data,'station-paris','BAJIE','OK',100);linkManufacturerStation(data,'station-lyon','BAJIE','FAIL',100);const attempts=new Map<string,number>(),repo=new MemoryRepository(data);const service=new ManufacturerSyncService(repo,{getDeviceInfo:async id=>{attempts.set(id,(attempts.get(id)??0)+1);if(id==='FAIL')throw new ManufacturerError('timeout',504,'TIMEOUT');if((attempts.get(id)??0)<2)throw new ManufacturerError('temporary',503,'UNAVAILABLE');return snapshot(id);}},{attempts:2,baseDelayMs:0,sleep:async()=>{}});const run=await service.run({trigger:'SCHEDULED'});assert.equal(run.status,'PARTIAL');assert.equal(run.succeeded,1);assert.equal(run.failed,1);assert.equal(attempts.get('OK'),2);assert.equal(attempts.get('FAIL'),2);});
test('scheduler lock rejects a concurrent second run and health uses only sync signals',async()=>{const data=seedData('x');linkManufacturerStation(data,'station-paris','BAJIE','LOCK',100);const repo=new MemoryRepository(data);let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve});let calls=0;const service=new ManufacturerSyncService(repo,{getDeviceInfo:async id=>{calls++;await gate;return snapshot(id);}},{now:()=>100,lockMs:60_000});const first=service.run({trigger:'SCHEDULED'});await new Promise(resolve=>setTimeout(resolve,0));const second=await service.run({trigger:'SCHEDULED'});assert.equal(second.skipped,true);release();const completed=await first;assert.equal(completed.status,'COMPLETED');assert.equal(calls,1);assert.equal(providerHealth(repo.data,100).status,'DEGRADED');});

test('partner dashboard cannot see another tenant manufacturer records',()=>{const data=seedData('x');const link=linkManufacturerStation(data,'station-paris','BAJIE','PARIS',100);data.reconciliationRecords.push({id:'rec',stationId:'station-paris',linkId:link.id,kind:'AVAILABILITY',position:null,localValue:2,providerValue:1,status:'OPEN',firstDetectedAt:100,lastDetectedAt:100,resolvedAt:null});const partnerB=dashboard(data,{id:'partner-b-demo',role:'PARTNER_ADMIN',partnerId:'partner-b'});assert.equal(partnerB.providerLinks.length,0);assert.equal(partnerB.reconciliationRecords.length,0);assert.equal(partnerB.manufacturerHealth.status,'UNKNOWN');});

test('manufacturer webhook is deduplicated, untrusted and only changes state after read-only reconciliation',async()=>{const data=seedData('x');linkManufacturerStation(data,'station-paris','BAJIE','BJH02347',100);const repo=new MemoryRepository(data),provider={getDeviceInfo:async(id:string)=>snapshot(id),listDevices:async()=>[]};const api=createApi(repo,{demo:true,allowLegacyCredentials:true},{manufacturerProvider:provider});const make=()=>new Request('https://batyeo.test/api/core/manufacturer/webhook',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({documentedShape:false,value:1})});const first=await api.POST(make(),{params:Promise.resolve({path:['manufacturer','webhook']})});assert.equal(first.status,202);assert.equal(repo.data.webhookEvents[0].status,'PROCESSED');assert.ok(repo.data.webhookEvents[0].source.startsWith('manufacturer:'));const second=await api.POST(make(),{params:Promise.resolve({path:['manufacturer','webhook']})});assert.equal((await second.json() as {duplicate:boolean}).duplicate,true);assert.equal(repo.data.webhookEvents.length,1);});
test('internal scheduler trigger is denied without secret and runs read-only with bearer secret',async()=>{const data=seedData('x');linkManufacturerStation(data,'station-paris','BAJIE','BJH02347',100);const repo=new MemoryRepository(data),provider={getDeviceInfo:async(id:string)=>snapshot(id),listDevices:async()=>[]},previous=process.env.MANUFACTURER_SYNC_SECRET;process.env.MANUFACTURER_SYNC_SECRET='staging-secret';try{const api=createApi(repo,{demo:false,allowLegacyCredentials:false},{manufacturerProvider:provider});const request=(secret?:string)=>new Request('https://batyeo.test/api/core/internal/manufacturer/sync',{method:'POST',headers:secret?{authorization:`Bearer ${secret}`}:{}});const denied=await api.POST(request('wrong'),{params:Promise.resolve({path:['internal','manufacturer','sync']})});assert.equal(denied.status,401);const accepted=await api.POST(request('staging-secret'),{params:Promise.resolve({path:['internal','manufacturer','sync']})});assert.equal(accepted.status,200);assert.equal(repo.data.manufacturerSyncRuns[0].trigger,'SCHEDULED');}finally{if(previous===undefined)delete process.env.MANUFACTURER_SYNC_SECRET;else process.env.MANUFACTURER_SYNC_SECRET=previous;}});
