import {test} from 'node:test';
import assert from 'node:assert/strict';
import {notificationPlan,parseStationQr,stationsNearby} from '../core/mobile';
import {reconcileRental,reconcileSnapshot} from '../core/reconciliation';
test('mobile QR parser accepts BATYEO station links and rejects foreign paths',()=>{assert.equal(parseStationQr('https://batyeo-web.anismeslin5.chatgpt.site/rent/paris-demo'),'paris-demo');assert.equal(parseStationQr('/rent/paris-demo'),null);assert.equal(parseStationQr('not a qr'),null);});
test('nearby stations are sorted by distance and exclude unknown coordinates',()=>{const stations=[{publicId:'far',name:'Far',city:'x',online:true,available:1,freeSlots:1,latitude:49,longitude:2},{publicId:'near',name:'Near',city:'x',online:true,available:1,freeSlots:1,latitude:48.8566,longitude:2.3522},{publicId:'unknown',name:'Unknown',city:'x',online:true,available:1,freeSlots:1}];assert.deepEqual(stationsNearby(stations,48.8566,2.3522,10).map(s=>s.publicId),['near']);});
test('notification plan is deterministic and never sends by itself',()=>{const now=1_700_000_000_000,deadline=now+24*3600000;const plan=notificationPlan('deadline_reminder',now,deadline);assert.equal(plan.scheduledAt,deadline-6*3600000);assert.equal(notificationPlan('receipt_ready',now).scheduledAt,null);});
test('reconciliation reports provider divergences without mutating state',()=>{assert.equal(reconcileRental('ACTIVE','RETURNED',0,0),'ACTIVE_BUT_PROVIDER_RETURNED');assert.equal(reconcileRental('COMPLETED','CAPTURED',0,400),'COMPLETED_BUT_CAPTURE_MISSING');assert.equal(reconcileRental('ACTIVE','UNKNOWN',0,0),'PROVIDER_UNAVAILABLE');assert.equal(reconcileRental('ACTIVE','ACTIVE',0,0),null);});
test('reconciliation detects payment/rental mismatches and missing events',()=>{const base={authorizedCents:2000,capturedCents:400,amountCents:400,providerState:'CAPTURED' as const,providerEventSeen:true};assert.equal(reconcileSnapshot({...base,rentalState:'ACTIVE',paymentStatus:'CAPTURED'}),'CAPTURE_WITHOUT_COMPLETED');assert.equal(reconcileSnapshot({...base,rentalState:'EJECTION_FAILED',paymentStatus:'AUTHORIZED'}),'AUTHORIZATION_OPEN_AFTER_EJECTION_FAILURE');assert.equal(reconcileSnapshot({...base,rentalState:'COMPLETED',paymentStatus:'CAPTURED',capturedCents:500}),'CAPTURE_AMOUNT_MISMATCH');assert.equal(reconcileSnapshot({...base,rentalState:'COMPLETED',paymentStatus:'CAPTURED',providerEventSeen:false}),'PAYMENT_EVENT_MISSING');});
