import {test} from 'node:test';
import assert from 'node:assert/strict';
import {StripePaymentProvider,StripeWebhookLedger,verifyStripeSignature, type StripeRequest} from '../core/stripe';
import {resolvePaymentMode} from '../core/payment-mode';

test('Stripe TEST provider uses manual capture and deterministic idempotency',async()=>{const requests:StripeRequest[]=[];const provider=new StripePaymentProvider('sk_test_demo',async request=>{requests.push(request);return {id:'pi_demo',status:'requires_capture',amount:2000};});await provider.authorize('rental-1',2000);await provider.capture('pi_demo',400,'rental-1');await provider.release('pi_demo','rental-1');assert.equal(requests[0].body.capture_method,'manual');assert.equal(requests[0].idempotencyKey,'rental-rental-1-authorize');assert.equal(requests[1].body.amount_to_capture,400);assert.equal(requests[2].path,'/payment_intents/pi_demo/cancel');});
test('Stripe webhook ledger ignores duplicate success and retries failed delivery',async()=>{const ledger=new StripeWebhookLedger();let calls=0;const event={id:'evt_1',type:'payment_intent.succeeded',created:1,data:{object:{}}};await ledger.process(event,()=>{calls++;});await ledger.process(event,()=>{calls++;});assert.equal(calls,1);await assert.rejects(()=>ledger.process({id:'evt_2',type:'x',created:1,data:{object:{}}},()=>{throw new Error('temporary');}));await ledger.process({id:'evt_2',type:'x',created:1,data:{object:{}}},()=>{calls++;});assert.equal(calls,2);});
test('Stripe webhook signature rejects stale or malformed deliveries',async()=>{assert.equal(await verifyStripeSignature('{}','t=1,v1=00','secret',1000),false);assert.equal(await verifyStripeSignature('{}','invalid','secret',1),false);});
test('payment provider guard defaults to mock and rejects live or incomplete Stripe config',()=>{assert.equal(resolvePaymentMode({}),'mock');assert.equal(resolvePaymentMode({BATYEO_PAYMENT_PROVIDER:'stripe_test',STRIPE_SECRET_KEY:'sk_test_demo'}),'stripe_test');assert.throws(()=>resolvePaymentMode({BATYEO_PAYMENT_PROVIDER:'stripe_live',STRIPE_SECRET_KEY:'sk_live_demo'}));assert.throws(()=>resolvePaymentMode({BATYEO_PAYMENT_PROVIDER:'stripe_test'}));});
