import type {Actor,Data,Rental} from './types';
import {authorize,inTenant} from './rental';
import {calculatePrice} from './pricing';
import {providerHealth} from './manufacturer-sync';
import type {StationPublicSnapshot} from './station-runtime';
import {evaluateAlerts} from './ops-alerts';
export function stationViews(d:Data){return d.stations.map(s=>({...s,venue:d.venues.find(v=>v.id===s.venueId)!,available:d.slots.filter(slot=>slot.stationId===s.id&&d.batteries.some(b=>b.id===slot.batteryId&&b.status==='AVAILABLE')).length,freeSlots:d.slots.filter(slot=>slot.stationId===s.id&&!slot.batteryId).length}));}
export function stationDisplaySnapshot(d:Data,stationId:string):StationPublicSnapshot {const station=stationViews(d).find(row=>row.id===stationId||row.publicId===stationId);if(!station)throw new Error('Station introuvable.');const pricing=d.pricing[0];if(!pricing)throw new Error('Tarification indisponible.');return {stationId:station.id,publicId:station.publicId,venueName:station.venue.name,online:station.online,availableBatteries:station.available,capacity:station.capacity,hourlyCents:pricing.hourlyCents,capCents:pricing.capCents,depositCents:pricing.depositCents,qrTarget:`/rent/${station.publicId}`,providerHealth:providerHealth(d).status};}
export const canViewFinance=(actor:Actor)=>['SUPER_ADMIN','ADMIN','FINANCE','PARTNER_ADMIN'].includes(actor.role);
export function rentalView(d:Data,r:Rental,financial=true){const elapsedMs=r.startedAt===null?0:Math.max(0,(r.returnedAt??Date.now())-r.startedAt+r.simulatedMinutes*60_000);return {...r,commissionCents:financial?r.commissionCents:undefined,customerId:undefined,idempotencyKey:undefined,elapsedMs,currentCents:r.startedAt===null?0:calculatePrice(elapsedMs,r.pricing),station:stationViews(d).find(s=>s.id===r.stationId),events:d.events.filter(e=>e.rentalId===r.id),payment:financial?d.payments.find(p=>p.rentalId===r.id):undefined};}
export function customerRentalView(d:Data,r:Rental){const view=rentalView(d,r,false);const payment=d.payments.find(p=>p.rentalId===r.id);return {...view,payment:payment?{authorizedCents:payment.authorizedCents,capturedCents:payment.capturedCents,releasedCents:payment.releasedCents,status:payment.status}:undefined};}
export function dashboard(d:Data,actor:Actor){
 authorize(actor,'read');const stations=stationViews(d).filter(s=>inTenant(actor,s.partnerId));const rentals=d.rentals.filter(r=>inTenant(actor,r.partnerId));const ids=new Set(rentals.map(r=>r.id));const stationIds=new Set(stations.map(s=>s.id));const batteryIds=new Set([...d.slots.filter(s=>stationIds.has(s.stationId)).map(s=>s.batteryId),...rentals.filter(r=>['ACTIVE','OVERDUE','LOST'].includes(r.state)).map(r=>r.batteryId)]);
 const canFinance=canViewFinance(actor);
 return {user:{...actor,name:d.users.find(u=>u.id===actor.id)?.name,email:d.users.find(u=>u.id===actor.id)?.email},stations,partners:d.partners.filter(p=>inTenant(actor,p.id)),venues:d.venues.filter(v=>inTenant(actor,v.partnerId)),rentals:rentals.map(r=>rentalView(d,r,canFinance)),batteries:d.batteries.filter(b=>batteryIds.has(b.id)),slots:d.slots.filter(s=>stationIds.has(s.stationId)),payments:canFinance?d.payments.filter(p=>ids.has(p.rentalId)):[],pricing:d.pricing[0],tickets:d.tickets.filter(t=>inTenant(actor,t.partnerId)),audits:actor.role.startsWith('PARTNER_')?[]:d.audits.slice(-50).reverse(),providerLinks:d.stationProviderLinks.filter(link=>stationIds.has(link.stationId)),providerSnapshots:d.stationProviderSnapshots.filter(snapshot=>stationIds.has(snapshot.stationId)),reconciliationRecords:d.reconciliationRecords.filter(record=>stationIds.has(record.stationId)),manufacturerSyncRuns:actor.role.startsWith('PARTNER_')?[]:d.manufacturerSyncRuns.slice(-20).reverse(),manufacturerHealth:actor.role.startsWith('PARTNER_')?{status:'UNKNOWN',lastSyncAt:null,recentFailures:0,openMismatches:d.reconciliationRecords.filter(record=>stationIds.has(record.stationId)&&record.status==='OPEN').length}:providerHealth(d),alerts:evaluateAlerts(d).filter(alert=>alert.stationId===null||stationIds.has(alert.stationId)),media:actor.role.startsWith('PARTNER_')?[]:d.media,serverTime:Date.now(),demo:true};
}
