import {DomainError} from './providers';

export interface StripeIntent {id:string;status:string;amount:number;amount_received?:number;metadata?:Record<string,string>;}
export interface StripeRequest {method:'POST';path:string;body:Record<string,unknown>;idempotencyKey:string;}
export type StripeTransport=(request:StripeRequest)=>Promise<StripeIntent>;

/** Stripe TEST boundary. The transport is injected so tests never contact Stripe. */
export class StripePaymentProvider {
 constructor(private readonly secretKey:string,private readonly transport:StripeTransport=(request)=>defaultTransport(secretKey,request)){if(!secretKey||!secretKey.startsWith('sk_test_'))throw new DomainError('Stripe TEST nécessite une clé sk_test_.',503);}
 async authorize(rentalId:string,cents:number):Promise<StripeIntent>{if(!Number.isSafeInteger(cents)||cents<=0)throw new DomainError('Montant d’autorisation invalide.');return this.call('/payment_intents',{amount:cents,currency:'eur',capture_method:'manual',metadata:{rentalId,provider:'batyeo'}},`rental-${rentalId}-authorize`);}
 async capture(intentId:string,cents:number,rentalId:string):Promise<StripeIntent>{if(!Number.isSafeInteger(cents)||cents<0)throw new DomainError('Montant de capture invalide.');return this.call(`/payment_intents/${encodeURIComponent(intentId)}/capture`,{amount_to_capture:cents,metadata:{rentalId}},`rental-${rentalId}-capture-${cents}`);}
 async release(intentId:string,rentalId:string):Promise<StripeIntent>{return this.call(`/payment_intents/${encodeURIComponent(intentId)}/cancel`,{},`rental-${rentalId}-release`);}
 private call(path:string,body:Record<string,unknown>,idempotencyKey:string){return this.transport({method:'POST',path,body,idempotencyKey}).catch(error=>{if(error instanceof DomainError)throw error;throw new DomainError('Stripe est temporairement indisponible.',503);});}
}
async function defaultTransport(secretKey:string,request:StripeRequest):Promise<StripeIntent>{const encoded=new URLSearchParams();for(const [key,value] of Object.entries(request.body)){if(typeof value==='object'&&value!==null)for(const [nested,nestedValue] of Object.entries(value))encoded.set(`${key}[${nested}]`,String(nestedValue));else encoded.set(key,String(value));}const response=await fetch(`https://api.stripe.com/v1${request.path}`,{method:'POST',headers:{Authorization:`Bearer ${secretKey}`,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':request.idempotencyKey},body:encoded});const payload=await response.json() as StripeIntent & {error?:{message?:string}};if(!response.ok)throw new DomainError(payload.error?.message??'Stripe a refusé l’opération.',response.status===402?402:503);return payload;}

export async function verifyStripeSignature(payload:string,header:string,secret:string,now=Math.floor(Date.now()/1000),tolerance=300):Promise<boolean>{const parts=Object.fromEntries(header.split(',').map(part=>part.split('='))) as Record<string,string>;const timestamp=Number(parts.t);const signature=parts.v1;if(!Number.isFinite(timestamp)||!signature||Math.abs(now-timestamp)>tolerance)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${timestamp}.${payload}`));const expected=Array.from(new Uint8Array(digest)).map(value=>value.toString(16).padStart(2,'0')).join('');if(expected.length!==signature.length)return false;let mismatch=0;for(let i=0;i<expected.length;i++)mismatch|=expected.charCodeAt(i)^signature.charCodeAt(i);return mismatch===0;}

export interface StripeWebhookEvent {id:string;type:string;created:number;data:{object:Record<string,unknown>};}
export type WebhookStatus='PROCESSED'|'FAILED';
/** Replace this ledger with the repository-backed WebhookEvent table in production. */
export class StripeWebhookLedger {private readonly events=new Map<string,{status:WebhookStatus;error?:string}>();async process(event:StripeWebhookEvent,handler:(event:StripeWebhookEvent)=>Promise<void>|void){const previous=this.events.get(event.id);if(previous?.status==='PROCESSED')return;if(previous?.status==='FAILED')this.events.delete(event.id);try{await handler(event);this.events.set(event.id,{status:'PROCESSED'});}catch(error){this.events.set(event.id,{status:'FAILED',error:error instanceof Error?error.message:'Unknown webhook error'});throw error;}}hasProcessed(id:string){return this.events.get(id)?.status==='PROCESSED';}}
