import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
const columns=()=>({id:text('id').primaryKey(),payload:text('payload').notNull()});
const record=(name:string)=>sqliteTable(name,columns());
export const revision=sqliteTable('revision',{id:integer('id').primaryKey(),version:integer('version').notNull(),token:text('token').notNull()});
export const users=record('users'); // Legacy preview fixture email dedup is an application repair.
export const partners=record('partners');
export const venues=record('venues');
export const stations=record('stations');
export const batteries=record('batteries');
export const events=record('events');
export const pricing=record('pricing');
export const tickets=record('tickets');
export const promos=record('promos');
export const audits=record('audits');
export const sessions=record('sessions');
export const limits=record('limits');
export const customerSessions=record('customerSessions');
export const customerHandoffTokens=record('customerHandoffTokens');
export const webhookEvents=record('webhookEvents');
export const stationProviderLinks=sqliteTable('stationProviderLinks',{...columns(),manufacturerKey:text('manufacturer_key').generatedAlwaysAs(sql`json_extract(payload, '$.manufacturer')`),externalKey:text('external_key').generatedAlwaysAs(sql`json_extract(payload, '$.externalId')`),stationKey:text('station_key').generatedAlwaysAs(sql`json_extract(payload, '$.stationId')`),activeKey:integer('active_key').generatedAlwaysAs(sql`json_extract(payload, '$.active')`)},t=>[uniqueIndex('provider_external_unique').on(t.manufacturerKey,t.externalKey),uniqueIndex('provider_station_active_unique').on(t.stationKey,t.manufacturerKey).where(sql`${t.activeKey} = 1`)]);
export const stationProviderSnapshots=sqliteTable('stationProviderSnapshots',{...columns(),linkKey:text('link_key').generatedAlwaysAs(sql`json_extract(payload, '$.linkId')`)},t=>[uniqueIndex('provider_snapshot_link_unique').on(t.linkKey)]);
export const reconciliationRecords=record('reconciliationRecords');
export const manufacturerSyncRuns=record('manufacturerSyncRuns');
export const runtimeCredentials=record('runtimeCredentials');
export const runtimeEnrollmentTokens=record('runtimeEnrollmentTokens');
export const hardwareDiscoveryReports=record('hardwareDiscoveryReports');
export const stationCapabilities=sqliteTable('stationCapabilities',{...columns(),stationKey:text('station_key').generatedAlwaysAs(sql`json_extract(payload, '$.stationId')`),capabilityKey:text('capability_key').generatedAlwaysAs(sql`json_extract(payload, '$.capability')`)},t=>[uniqueIndex('station_capability_unique').on(t.stationKey,t.capabilityKey)]);
export const partnerUsers=sqliteTable('partnerUsers',{...columns(),userKey:text('user_key').generatedAlwaysAs(sql`json_extract(payload, '$.userId')`),partnerKey:text('partner_key').generatedAlwaysAs(sql`json_extract(payload, '$.partnerId')`)},t=>[uniqueIndex('membership_unique').on(t.userKey,t.partnerKey)]);
export const slots=sqliteTable('slots',{...columns(),batteryKey:text('battery_key').generatedAlwaysAs(sql`json_extract(payload, '$.batteryId')`),stationKey:text('station_key').generatedAlwaysAs(sql`json_extract(payload, '$.stationId')`),slotPosition:integer('slot_position').generatedAlwaysAs(sql`json_extract(payload, '$.position')`)},t=>[uniqueIndex('slots_battery_unique').on(t.batteryKey),uniqueIndex('slots_position_unique').on(t.stationKey,t.slotPosition)]);
export const rentals=sqliteTable('rentals',{...columns(),customerKey:text('customer_key').generatedAlwaysAs(sql`json_extract(payload, '$.customerId')`),batteryKey:text('battery_key').generatedAlwaysAs(sql`json_extract(payload, '$.batteryId')`),idempotencyKey:text('idempotency_key').generatedAlwaysAs(sql`json_extract(payload, '$.idempotencyKey')`),partnerKey:text('partner_key').generatedAlwaysAs(sql`json_extract(payload, '$.partnerId')`),createdTime:integer('created_time').generatedAlwaysAs(sql`json_extract(payload, '$.createdAt')`),rentalState:text('rental_state').generatedAlwaysAs(sql`json_extract(payload, '$.state')`)},t=>[uniqueIndex('rentals_idempotency_unique').on(t.customerKey,t.idempotencyKey),uniqueIndex('rentals_open_customer_unique').on(t.customerKey).where(sql`${t.rentalState} IN ('CREATED','PAYMENT_AUTH','EJECTING','ACTIVE','RETURN_PENDING','RETURNED','OVERDUE','ERROR')`),uniqueIndex('rentals_open_battery_unique').on(t.batteryKey).where(sql`${t.rentalState} IN ('CREATED','PAYMENT_AUTH','EJECTING','ACTIVE','RETURN_PENDING','RETURNED','OVERDUE','ERROR')`),index('rentals_tenant_created').on(t.partnerKey,t.createdTime)]);
export const payments=sqliteTable('payments',{...columns(),rentalKey:text('rental_key').generatedAlwaysAs(sql`json_extract(payload, '$.rentalId')`)},t=>[uniqueIndex('payments_rental_unique').on(t.rentalKey)]);
export const terms=sqliteTable('terms',{...columns(),rentalKey:text('rental_key').generatedAlwaysAs(sql`json_extract(payload, '$.rentalId')`)},t=>[uniqueIndex('terms_rental_unique').on(t.rentalKey)]);
